/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as InternalGateRouteImport } from './routes/_internalGate'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as PortalTokenRouteImport } from './routes/portal.$token'
import { Route as InternalLoginRouteImport } from './routes/internal.login'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as MarketingDocsRouteImport } from './routes/_marketing/docs'
import { Route as DashboardRevenueRouteImport } from './routes/_dashboard/revenue'
import { Route as DashboardOverviewRouteImport } from './routes/_dashboard/overview'
import { Route as DashboardEventsRouteImport } from './routes/_dashboard/events'
import { Route as DashboardAnalyticsRouteImport } from './routes/_dashboard/analytics'
import { Route as PortalTokenIndexRouteImport } from './routes/portal.$token/index'
import { Route as InternalGateInternalIndexRouteImport } from './routes/_internalGate/internal/index'
import { Route as DashboardWebhooksIndexRouteImport } from './routes/_dashboard/webhooks/index'
import { Route as DashboardSubscriptionsIndexRouteImport } from './routes/_dashboard/subscriptions/index'
import { Route as DashboardPlansIndexRouteImport } from './routes/_dashboard/plans/index'
import { Route as DashboardPayoutsIndexRouteImport } from './routes/_dashboard/payouts/index'
import { Route as DashboardInvoicesIndexRouteImport } from './routes/_dashboard/invoices/index'
import { Route as DashboardCustomersIndexRouteImport } from './routes/_dashboard/customers/index'
import { Route as PortalTokenPlansRouteImport } from './routes/portal.$token/plans'
import { Route as PortalTokenInvoicesRouteImport } from './routes/portal.$token/invoices'
import { Route as PortalTokenCardUpdatedRouteImport } from './routes/portal.$token/card-updated'
import { Route as PayMerchantSlugPlanSlugRouteImport } from './routes/pay.$merchantSlug.$planSlug'
import { Route as InternalGateInternalFeesRouteImport } from './routes/_internalGate/internal/fees'
import { Route as InternalGateInternalAuditLogRouteImport } from './routes/_internalGate/internal/audit-log'
import { Route as DashboardWebhooksDeliveriesRouteImport } from './routes/_dashboard/webhooks/deliveries'
import { Route as DashboardSubscriptionsSubscriptionIdRouteImport } from './routes/_dashboard/subscriptions/$subscriptionId'
import { Route as DashboardSettingsDunningRouteImport } from './routes/_dashboard/settings/dunning'
import { Route as DashboardSettingsAuditLogRouteImport } from './routes/_dashboard/settings/audit-log'
import { Route as DashboardSettingsApiKeysRouteImport } from './routes/_dashboard/settings/api-keys'
import { Route as DashboardSettingsAccountRouteImport } from './routes/_dashboard/settings/account'
import { Route as DashboardPlansNewRouteImport } from './routes/_dashboard/plans/new'
import { Route as DashboardPlansPlanIdRouteImport } from './routes/_dashboard/plans/$planId'
import { Route as DashboardInvoicesInvoiceIdRouteImport } from './routes/_dashboard/invoices/$invoiceId'
import { Route as DashboardCustomersCustomerIdRouteImport } from './routes/_dashboard/customers/$customerId'
import { Route as InternalGateInternalRefundsIndexRouteImport } from './routes/_internalGate/internal/refunds/index'
import { Route as InternalGateInternalMerchantsIndexRouteImport } from './routes/_internalGate/internal/merchants/index'
import { Route as PlansMerchantSlugPlanSlugSuccessRouteImport } from './routes/plans.$merchantSlug.$planSlug.success'
import { Route as InternalGateInternalMerchantsMerchantIdRouteImport } from './routes/_internalGate/internal/merchants/$merchantId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalGateRoute = InternalGateRouteImport.update({
  id: '/_internalGate',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const PortalTokenRoute = PortalTokenRouteImport.update({
  id: '/portal/$token',
  path: '/portal/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalLoginRoute = InternalLoginRouteImport.update({
  id: '/internal/login',
  path: '/internal/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const MarketingDocsRoute = MarketingDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => MarketingRoute,
} as any)
const DashboardRevenueRoute = DashboardRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOverviewRoute = DashboardOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEventsRoute = DashboardEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const PortalTokenIndexRoute = PortalTokenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalTokenRoute,
} as any)
const InternalGateInternalIndexRoute =
  InternalGateInternalIndexRouteImport.update({
    id: '/internal/',
    path: '/internal/',
    getParentRoute: () => InternalGateRoute,
  } as any)
const DashboardWebhooksIndexRoute = DashboardWebhooksIndexRouteImport.update({
  id: '/webhooks/',
  path: '/webhooks/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSubscriptionsIndexRoute =
  DashboardSubscriptionsIndexRouteImport.update({
    id: '/subscriptions/',
    path: '/subscriptions/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPlansIndexRoute = DashboardPlansIndexRouteImport.update({
  id: '/plans/',
  path: '/plans/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPayoutsIndexRoute = DashboardPayoutsIndexRouteImport.update({
  id: '/payouts/',
  path: '/payouts/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInvoicesIndexRoute = DashboardInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCustomersIndexRoute = DashboardCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => DashboardRoute,
} as any)
const PortalTokenPlansRoute = PortalTokenPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => PortalTokenRoute,
} as any)
const PortalTokenInvoicesRoute = PortalTokenInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => PortalTokenRoute,
} as any)
const PortalTokenCardUpdatedRoute = PortalTokenCardUpdatedRouteImport.update({
  id: '/card-updated',
  path: '/card-updated',
  getParentRoute: () => PortalTokenRoute,
} as any)
const PayMerchantSlugPlanSlugRoute = PayMerchantSlugPlanSlugRouteImport.update({
  id: '/pay/$merchantSlug/$planSlug',
  path: '/pay/$merchantSlug/$planSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalGateInternalFeesRoute =
  InternalGateInternalFeesRouteImport.update({
    id: '/internal/fees',
    path: '/internal/fees',
    getParentRoute: () => InternalGateRoute,
  } as any)
const InternalGateInternalAuditLogRoute =
  InternalGateInternalAuditLogRouteImport.update({
    id: '/internal/audit-log',
    path: '/internal/audit-log',
    getParentRoute: () => InternalGateRoute,
  } as any)
const DashboardWebhooksDeliveriesRoute =
  DashboardWebhooksDeliveriesRouteImport.update({
    id: '/webhooks/deliveries',
    path: '/webhooks/deliveries',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSubscriptionsSubscriptionIdRoute =
  DashboardSubscriptionsSubscriptionIdRouteImport.update({
    id: '/subscriptions/$subscriptionId',
    path: '/subscriptions/$subscriptionId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSettingsDunningRoute =
  DashboardSettingsDunningRouteImport.update({
    id: '/settings/dunning',
    path: '/settings/dunning',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSettingsAuditLogRoute =
  DashboardSettingsAuditLogRouteImport.update({
    id: '/settings/audit-log',
    path: '/settings/audit-log',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSettingsApiKeysRoute =
  DashboardSettingsApiKeysRouteImport.update({
    id: '/settings/api-keys',
    path: '/settings/api-keys',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSettingsAccountRoute =
  DashboardSettingsAccountRouteImport.update({
    id: '/settings/account',
    path: '/settings/account',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPlansNewRoute = DashboardPlansNewRouteImport.update({
  id: '/plans/new',
  path: '/plans/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlansPlanIdRoute = DashboardPlansPlanIdRouteImport.update({
  id: '/plans/$planId',
  path: '/plans/$planId',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInvoicesInvoiceIdRoute =
  DashboardInvoicesInvoiceIdRouteImport.update({
    id: '/invoices/$invoiceId',
    path: '/invoices/$invoiceId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardCustomersCustomerIdRoute =
  DashboardCustomersCustomerIdRouteImport.update({
    id: '/customers/$customerId',
    path: '/customers/$customerId',
    getParentRoute: () => DashboardRoute,
  } as any)
const InternalGateInternalRefundsIndexRoute =
  InternalGateInternalRefundsIndexRouteImport.update({
    id: '/internal/refunds/',
    path: '/internal/refunds/',
    getParentRoute: () => InternalGateRoute,
  } as any)
const InternalGateInternalMerchantsIndexRoute =
  InternalGateInternalMerchantsIndexRouteImport.update({
    id: '/internal/merchants/',
    path: '/internal/merchants/',
    getParentRoute: () => InternalGateRoute,
  } as any)
const PlansMerchantSlugPlanSlugSuccessRoute =
  PlansMerchantSlugPlanSlugSuccessRouteImport.update({
    id: '/plans/$merchantSlug/$planSlug/success',
    path: '/plans/$merchantSlug/$planSlug/success',
    getParentRoute: () => rootRouteImport,
  } as any)
const InternalGateInternalMerchantsMerchantIdRoute =
  InternalGateInternalMerchantsMerchantIdRouteImport.update({
    id: '/internal/merchants/$merchantId',
    path: '/internal/merchants/$merchantId',
    getParentRoute: () => InternalGateRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/analytics': typeof DashboardAnalyticsRoute
  '/events': typeof DashboardEventsRoute
  '/overview': typeof DashboardOverviewRoute
  '/revenue': typeof DashboardRevenueRoute
  '/docs': typeof MarketingDocsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/internal/login': typeof InternalLoginRoute
  '/portal/$token': typeof PortalTokenRouteWithChildren
  '/customers/$customerId': typeof DashboardCustomersCustomerIdRoute
  '/invoices/$invoiceId': typeof DashboardInvoicesInvoiceIdRoute
  '/plans/$planId': typeof DashboardPlansPlanIdRoute
  '/plans/new': typeof DashboardPlansNewRoute
  '/settings/account': typeof DashboardSettingsAccountRoute
  '/settings/api-keys': typeof DashboardSettingsApiKeysRoute
  '/settings/audit-log': typeof DashboardSettingsAuditLogRoute
  '/settings/dunning': typeof DashboardSettingsDunningRoute
  '/subscriptions/$subscriptionId': typeof DashboardSubscriptionsSubscriptionIdRoute
  '/webhooks/deliveries': typeof DashboardWebhooksDeliveriesRoute
  '/internal/audit-log': typeof InternalGateInternalAuditLogRoute
  '/internal/fees': typeof InternalGateInternalFeesRoute
  '/pay/$merchantSlug/$planSlug': typeof PayMerchantSlugPlanSlugRoute
  '/portal/$token/card-updated': typeof PortalTokenCardUpdatedRoute
  '/portal/$token/invoices': typeof PortalTokenInvoicesRoute
  '/portal/$token/plans': typeof PortalTokenPlansRoute
  '/customers/': typeof DashboardCustomersIndexRoute
  '/invoices/': typeof DashboardInvoicesIndexRoute
  '/payouts/': typeof DashboardPayoutsIndexRoute
  '/plans/': typeof DashboardPlansIndexRoute
  '/subscriptions/': typeof DashboardSubscriptionsIndexRoute
  '/webhooks/': typeof DashboardWebhooksIndexRoute
  '/internal/': typeof InternalGateInternalIndexRoute
  '/portal/$token/': typeof PortalTokenIndexRoute
  '/internal/merchants/$merchantId': typeof InternalGateInternalMerchantsMerchantIdRoute
  '/plans/$merchantSlug/$planSlug/success': typeof PlansMerchantSlugPlanSlugSuccessRoute
  '/internal/merchants/': typeof InternalGateInternalMerchantsIndexRoute
  '/internal/refunds/': typeof InternalGateInternalRefundsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof MarketingIndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/analytics': typeof DashboardAnalyticsRoute
  '/events': typeof DashboardEventsRoute
  '/overview': typeof DashboardOverviewRoute
  '/revenue': typeof DashboardRevenueRoute
  '/docs': typeof MarketingDocsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/internal/login': typeof InternalLoginRoute
  '/customers/$customerId': typeof DashboardCustomersCustomerIdRoute
  '/invoices/$invoiceId': typeof DashboardInvoicesInvoiceIdRoute
  '/plans/$planId': typeof DashboardPlansPlanIdRoute
  '/plans/new': typeof DashboardPlansNewRoute
  '/settings/account': typeof DashboardSettingsAccountRoute
  '/settings/api-keys': typeof DashboardSettingsApiKeysRoute
  '/settings/audit-log': typeof DashboardSettingsAuditLogRoute
  '/settings/dunning': typeof DashboardSettingsDunningRoute
  '/subscriptions/$subscriptionId': typeof DashboardSubscriptionsSubscriptionIdRoute
  '/webhooks/deliveries': typeof DashboardWebhooksDeliveriesRoute
  '/internal/audit-log': typeof InternalGateInternalAuditLogRoute
  '/internal/fees': typeof InternalGateInternalFeesRoute
  '/pay/$merchantSlug/$planSlug': typeof PayMerchantSlugPlanSlugRoute
  '/portal/$token/card-updated': typeof PortalTokenCardUpdatedRoute
  '/portal/$token/invoices': typeof PortalTokenInvoicesRoute
  '/portal/$token/plans': typeof PortalTokenPlansRoute
  '/customers': typeof DashboardCustomersIndexRoute
  '/invoices': typeof DashboardInvoicesIndexRoute
  '/payouts': typeof DashboardPayoutsIndexRoute
  '/plans': typeof DashboardPlansIndexRoute
  '/subscriptions': typeof DashboardSubscriptionsIndexRoute
  '/webhooks': typeof DashboardWebhooksIndexRoute
  '/internal': typeof InternalGateInternalIndexRoute
  '/portal/$token': typeof PortalTokenIndexRoute
  '/internal/merchants/$merchantId': typeof InternalGateInternalMerchantsMerchantIdRoute
  '/plans/$merchantSlug/$planSlug/success': typeof PlansMerchantSlugPlanSlugSuccessRoute
  '/internal/merchants': typeof InternalGateInternalMerchantsIndexRoute
  '/internal/refunds': typeof InternalGateInternalRefundsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_internalGate': typeof InternalGateRouteWithChildren
  '/_marketing': typeof MarketingRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_dashboard/analytics': typeof DashboardAnalyticsRoute
  '/_dashboard/events': typeof DashboardEventsRoute
  '/_dashboard/overview': typeof DashboardOverviewRoute
  '/_dashboard/revenue': typeof DashboardRevenueRoute
  '/_marketing/docs': typeof MarketingDocsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/internal/login': typeof InternalLoginRoute
  '/portal/$token': typeof PortalTokenRouteWithChildren
  '/_marketing/': typeof MarketingIndexRoute
  '/_dashboard/customers/$customerId': typeof DashboardCustomersCustomerIdRoute
  '/_dashboard/invoices/$invoiceId': typeof DashboardInvoicesInvoiceIdRoute
  '/_dashboard/plans/$planId': typeof DashboardPlansPlanIdRoute
  '/_dashboard/plans/new': typeof DashboardPlansNewRoute
  '/_dashboard/settings/account': typeof DashboardSettingsAccountRoute
  '/_dashboard/settings/api-keys': typeof DashboardSettingsApiKeysRoute
  '/_dashboard/settings/audit-log': typeof DashboardSettingsAuditLogRoute
  '/_dashboard/settings/dunning': typeof DashboardSettingsDunningRoute
  '/_dashboard/subscriptions/$subscriptionId': typeof DashboardSubscriptionsSubscriptionIdRoute
  '/_dashboard/webhooks/deliveries': typeof DashboardWebhooksDeliveriesRoute
  '/_internalGate/internal/audit-log': typeof InternalGateInternalAuditLogRoute
  '/_internalGate/internal/fees': typeof InternalGateInternalFeesRoute
  '/pay/$merchantSlug/$planSlug': typeof PayMerchantSlugPlanSlugRoute
  '/portal/$token/card-updated': typeof PortalTokenCardUpdatedRoute
  '/portal/$token/invoices': typeof PortalTokenInvoicesRoute
  '/portal/$token/plans': typeof PortalTokenPlansRoute
  '/_dashboard/customers/': typeof DashboardCustomersIndexRoute
  '/_dashboard/invoices/': typeof DashboardInvoicesIndexRoute
  '/_dashboard/payouts/': typeof DashboardPayoutsIndexRoute
  '/_dashboard/plans/': typeof DashboardPlansIndexRoute
  '/_dashboard/subscriptions/': typeof DashboardSubscriptionsIndexRoute
  '/_dashboard/webhooks/': typeof DashboardWebhooksIndexRoute
  '/_internalGate/internal/': typeof InternalGateInternalIndexRoute
  '/portal/$token/': typeof PortalTokenIndexRoute
  '/_internalGate/internal/merchants/$merchantId': typeof InternalGateInternalMerchantsMerchantIdRoute
  '/plans/$merchantSlug/$planSlug/success': typeof PlansMerchantSlugPlanSlugSuccessRoute
  '/_internalGate/internal/merchants/': typeof InternalGateInternalMerchantsIndexRoute
  '/_internalGate/internal/refunds/': typeof InternalGateInternalRefundsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/analytics'
    | '/events'
    | '/overview'
    | '/revenue'
    | '/docs'
    | '/auth/login'
    | '/auth/signup'
    | '/internal/login'
    | '/portal/$token'
    | '/customers/$customerId'
    | '/invoices/$invoiceId'
    | '/plans/$planId'
    | '/plans/new'
    | '/settings/account'
    | '/settings/api-keys'
    | '/settings/audit-log'
    | '/settings/dunning'
    | '/subscriptions/$subscriptionId'
    | '/webhooks/deliveries'
    | '/internal/audit-log'
    | '/internal/fees'
    | '/pay/$merchantSlug/$planSlug'
    | '/portal/$token/card-updated'
    | '/portal/$token/invoices'
    | '/portal/$token/plans'
    | '/customers/'
    | '/invoices/'
    | '/payouts/'
    | '/plans/'
    | '/subscriptions/'
    | '/webhooks/'
    | '/internal/'
    | '/portal/$token/'
    | '/internal/merchants/$merchantId'
    | '/plans/$merchantSlug/$planSlug/success'
    | '/internal/merchants/'
    | '/internal/refunds/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/analytics'
    | '/events'
    | '/overview'
    | '/revenue'
    | '/docs'
    | '/auth/login'
    | '/auth/signup'
    | '/internal/login'
    | '/customers/$customerId'
    | '/invoices/$invoiceId'
    | '/plans/$planId'
    | '/plans/new'
    | '/settings/account'
    | '/settings/api-keys'
    | '/settings/audit-log'
    | '/settings/dunning'
    | '/subscriptions/$subscriptionId'
    | '/webhooks/deliveries'
    | '/internal/audit-log'
    | '/internal/fees'
    | '/pay/$merchantSlug/$planSlug'
    | '/portal/$token/card-updated'
    | '/portal/$token/invoices'
    | '/portal/$token/plans'
    | '/customers'
    | '/invoices'
    | '/payouts'
    | '/plans'
    | '/subscriptions'
    | '/webhooks'
    | '/internal'
    | '/portal/$token'
    | '/internal/merchants/$merchantId'
    | '/plans/$merchantSlug/$planSlug/success'
    | '/internal/merchants'
    | '/internal/refunds'
  id:
    | '__root__'
    | '/_dashboard'
    | '/_internalGate'
    | '/_marketing'
    | '/auth'
    | '/_dashboard/analytics'
    | '/_dashboard/events'
    | '/_dashboard/overview'
    | '/_dashboard/revenue'
    | '/_marketing/docs'
    | '/auth/login'
    | '/auth/signup'
    | '/internal/login'
    | '/portal/$token'
    | '/_marketing/'
    | '/_dashboard/customers/$customerId'
    | '/_dashboard/invoices/$invoiceId'
    | '/_dashboard/plans/$planId'
    | '/_dashboard/plans/new'
    | '/_dashboard/settings/account'
    | '/_dashboard/settings/api-keys'
    | '/_dashboard/settings/audit-log'
    | '/_dashboard/settings/dunning'
    | '/_dashboard/subscriptions/$subscriptionId'
    | '/_dashboard/webhooks/deliveries'
    | '/_internalGate/internal/audit-log'
    | '/_internalGate/internal/fees'
    | '/pay/$merchantSlug/$planSlug'
    | '/portal/$token/card-updated'
    | '/portal/$token/invoices'
    | '/portal/$token/plans'
    | '/_dashboard/customers/'
    | '/_dashboard/invoices/'
    | '/_dashboard/payouts/'
    | '/_dashboard/plans/'
    | '/_dashboard/subscriptions/'
    | '/_dashboard/webhooks/'
    | '/_internalGate/internal/'
    | '/portal/$token/'
    | '/_internalGate/internal/merchants/$merchantId'
    | '/plans/$merchantSlug/$planSlug/success'
    | '/_internalGate/internal/merchants/'
    | '/_internalGate/internal/refunds/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  InternalGateRoute: typeof InternalGateRouteWithChildren
  MarketingRoute: typeof MarketingRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  InternalLoginRoute: typeof InternalLoginRoute
  PortalTokenRoute: typeof PortalTokenRouteWithChildren
  PayMerchantSlugPlanSlugRoute: typeof PayMerchantSlugPlanSlugRoute
  PlansMerchantSlugPlanSlugSuccessRoute: typeof PlansMerchantSlugPlanSlugSuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_internalGate': {
      id: '/_internalGate'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof InternalGateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/portal/$token': {
      id: '/portal/$token'
      path: '/portal/$token'
      fullPath: '/portal/$token'
      preLoaderRoute: typeof PortalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/login': {
      id: '/internal/login'
      path: '/internal/login'
      fullPath: '/internal/login'
      preLoaderRoute: typeof InternalLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_marketing/docs': {
      id: '/_marketing/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof MarketingDocsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_dashboard/revenue': {
      id: '/_dashboard/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof DashboardRevenueRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/overview': {
      id: '/_dashboard/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof DashboardOverviewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/events': {
      id: '/_dashboard/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof DashboardEventsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/analytics': {
      id: '/_dashboard/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/portal/$token/': {
      id: '/portal/$token/'
      path: '/'
      fullPath: '/portal/$token/'
      preLoaderRoute: typeof PortalTokenIndexRouteImport
      parentRoute: typeof PortalTokenRoute
    }
    '/_internalGate/internal/': {
      id: '/_internalGate/internal/'
      path: '/internal'
      fullPath: '/internal/'
      preLoaderRoute: typeof InternalGateInternalIndexRouteImport
      parentRoute: typeof InternalGateRoute
    }
    '/_dashboard/webhooks/': {
      id: '/_dashboard/webhooks/'
      path: '/webhooks'
      fullPath: '/webhooks/'
      preLoaderRoute: typeof DashboardWebhooksIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/subscriptions/': {
      id: '/_dashboard/subscriptions/'
      path: '/subscriptions'
      fullPath: '/subscriptions/'
      preLoaderRoute: typeof DashboardSubscriptionsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/plans/': {
      id: '/_dashboard/plans/'
      path: '/plans'
      fullPath: '/plans/'
      preLoaderRoute: typeof DashboardPlansIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/payouts/': {
      id: '/_dashboard/payouts/'
      path: '/payouts'
      fullPath: '/payouts/'
      preLoaderRoute: typeof DashboardPayoutsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/invoices/': {
      id: '/_dashboard/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof DashboardInvoicesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/customers/': {
      id: '/_dashboard/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof DashboardCustomersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/portal/$token/plans': {
      id: '/portal/$token/plans'
      path: '/plans'
      fullPath: '/portal/$token/plans'
      preLoaderRoute: typeof PortalTokenPlansRouteImport
      parentRoute: typeof PortalTokenRoute
    }
    '/portal/$token/invoices': {
      id: '/portal/$token/invoices'
      path: '/invoices'
      fullPath: '/portal/$token/invoices'
      preLoaderRoute: typeof PortalTokenInvoicesRouteImport
      parentRoute: typeof PortalTokenRoute
    }
    '/portal/$token/card-updated': {
      id: '/portal/$token/card-updated'
      path: '/card-updated'
      fullPath: '/portal/$token/card-updated'
      preLoaderRoute: typeof PortalTokenCardUpdatedRouteImport
      parentRoute: typeof PortalTokenRoute
    }
    '/pay/$merchantSlug/$planSlug': {
      id: '/pay/$merchantSlug/$planSlug'
      path: '/pay/$merchantSlug/$planSlug'
      fullPath: '/pay/$merchantSlug/$planSlug'
      preLoaderRoute: typeof PayMerchantSlugPlanSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_internalGate/internal/fees': {
      id: '/_internalGate/internal/fees'
      path: '/internal/fees'
      fullPath: '/internal/fees'
      preLoaderRoute: typeof InternalGateInternalFeesRouteImport
      parentRoute: typeof InternalGateRoute
    }
    '/_internalGate/internal/audit-log': {
      id: '/_internalGate/internal/audit-log'
      path: '/internal/audit-log'
      fullPath: '/internal/audit-log'
      preLoaderRoute: typeof InternalGateInternalAuditLogRouteImport
      parentRoute: typeof InternalGateRoute
    }
    '/_dashboard/webhooks/deliveries': {
      id: '/_dashboard/webhooks/deliveries'
      path: '/webhooks/deliveries'
      fullPath: '/webhooks/deliveries'
      preLoaderRoute: typeof DashboardWebhooksDeliveriesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/subscriptions/$subscriptionId': {
      id: '/_dashboard/subscriptions/$subscriptionId'
      path: '/subscriptions/$subscriptionId'
      fullPath: '/subscriptions/$subscriptionId'
      preLoaderRoute: typeof DashboardSubscriptionsSubscriptionIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings/dunning': {
      id: '/_dashboard/settings/dunning'
      path: '/settings/dunning'
      fullPath: '/settings/dunning'
      preLoaderRoute: typeof DashboardSettingsDunningRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings/audit-log': {
      id: '/_dashboard/settings/audit-log'
      path: '/settings/audit-log'
      fullPath: '/settings/audit-log'
      preLoaderRoute: typeof DashboardSettingsAuditLogRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings/api-keys': {
      id: '/_dashboard/settings/api-keys'
      path: '/settings/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof DashboardSettingsApiKeysRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings/account': {
      id: '/_dashboard/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof DashboardSettingsAccountRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/plans/new': {
      id: '/_dashboard/plans/new'
      path: '/plans/new'
      fullPath: '/plans/new'
      preLoaderRoute: typeof DashboardPlansNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/plans/$planId': {
      id: '/_dashboard/plans/$planId'
      path: '/plans/$planId'
      fullPath: '/plans/$planId'
      preLoaderRoute: typeof DashboardPlansPlanIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/invoices/$invoiceId': {
      id: '/_dashboard/invoices/$invoiceId'
      path: '/invoices/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof DashboardInvoicesInvoiceIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/customers/$customerId': {
      id: '/_dashboard/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof DashboardCustomersCustomerIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_internalGate/internal/refunds/': {
      id: '/_internalGate/internal/refunds/'
      path: '/internal/refunds'
      fullPath: '/internal/refunds/'
      preLoaderRoute: typeof InternalGateInternalRefundsIndexRouteImport
      parentRoute: typeof InternalGateRoute
    }
    '/_internalGate/internal/merchants/': {
      id: '/_internalGate/internal/merchants/'
      path: '/internal/merchants'
      fullPath: '/internal/merchants/'
      preLoaderRoute: typeof InternalGateInternalMerchantsIndexRouteImport
      parentRoute: typeof InternalGateRoute
    }
    '/plans/$merchantSlug/$planSlug/success': {
      id: '/plans/$merchantSlug/$planSlug/success'
      path: '/plans/$merchantSlug/$planSlug/success'
      fullPath: '/plans/$merchantSlug/$planSlug/success'
      preLoaderRoute: typeof PlansMerchantSlugPlanSlugSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_internalGate/internal/merchants/$merchantId': {
      id: '/_internalGate/internal/merchants/$merchantId'
      path: '/internal/merchants/$merchantId'
      fullPath: '/internal/merchants/$merchantId'
      preLoaderRoute: typeof InternalGateInternalMerchantsMerchantIdRouteImport
      parentRoute: typeof InternalGateRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardEventsRoute: typeof DashboardEventsRoute
  DashboardOverviewRoute: typeof DashboardOverviewRoute
  DashboardRevenueRoute: typeof DashboardRevenueRoute
  DashboardCustomersCustomerIdRoute: typeof DashboardCustomersCustomerIdRoute
  DashboardInvoicesInvoiceIdRoute: typeof DashboardInvoicesInvoiceIdRoute
  DashboardPlansPlanIdRoute: typeof DashboardPlansPlanIdRoute
  DashboardPlansNewRoute: typeof DashboardPlansNewRoute
  DashboardSettingsAccountRoute: typeof DashboardSettingsAccountRoute
  DashboardSettingsApiKeysRoute: typeof DashboardSettingsApiKeysRoute
  DashboardSettingsAuditLogRoute: typeof DashboardSettingsAuditLogRoute
  DashboardSettingsDunningRoute: typeof DashboardSettingsDunningRoute
  DashboardSubscriptionsSubscriptionIdRoute: typeof DashboardSubscriptionsSubscriptionIdRoute
  DashboardWebhooksDeliveriesRoute: typeof DashboardWebhooksDeliveriesRoute
  DashboardCustomersIndexRoute: typeof DashboardCustomersIndexRoute
  DashboardInvoicesIndexRoute: typeof DashboardInvoicesIndexRoute
  DashboardPayoutsIndexRoute: typeof DashboardPayoutsIndexRoute
  DashboardPlansIndexRoute: typeof DashboardPlansIndexRoute
  DashboardSubscriptionsIndexRoute: typeof DashboardSubscriptionsIndexRoute
  DashboardWebhooksIndexRoute: typeof DashboardWebhooksIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardEventsRoute: DashboardEventsRoute,
  DashboardOverviewRoute: DashboardOverviewRoute,
  DashboardRevenueRoute: DashboardRevenueRoute,
  DashboardCustomersCustomerIdRoute: DashboardCustomersCustomerIdRoute,
  DashboardInvoicesInvoiceIdRoute: DashboardInvoicesInvoiceIdRoute,
  DashboardPlansPlanIdRoute: DashboardPlansPlanIdRoute,
  DashboardPlansNewRoute: DashboardPlansNewRoute,
  DashboardSettingsAccountRoute: DashboardSettingsAccountRoute,
  DashboardSettingsApiKeysRoute: DashboardSettingsApiKeysRoute,
  DashboardSettingsAuditLogRoute: DashboardSettingsAuditLogRoute,
  DashboardSettingsDunningRoute: DashboardSettingsDunningRoute,
  DashboardSubscriptionsSubscriptionIdRoute:
    DashboardSubscriptionsSubscriptionIdRoute,
  DashboardWebhooksDeliveriesRoute: DashboardWebhooksDeliveriesRoute,
  DashboardCustomersIndexRoute: DashboardCustomersIndexRoute,
  DashboardInvoicesIndexRoute: DashboardInvoicesIndexRoute,
  DashboardPayoutsIndexRoute: DashboardPayoutsIndexRoute,
  DashboardPlansIndexRoute: DashboardPlansIndexRoute,
  DashboardSubscriptionsIndexRoute: DashboardSubscriptionsIndexRoute,
  DashboardWebhooksIndexRoute: DashboardWebhooksIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface InternalGateRouteChildren {
  InternalGateInternalAuditLogRoute: typeof InternalGateInternalAuditLogRoute
  InternalGateInternalFeesRoute: typeof InternalGateInternalFeesRoute
  InternalGateInternalIndexRoute: typeof InternalGateInternalIndexRoute
  InternalGateInternalMerchantsMerchantIdRoute: typeof InternalGateInternalMerchantsMerchantIdRoute
  InternalGateInternalMerchantsIndexRoute: typeof InternalGateInternalMerchantsIndexRoute
  InternalGateInternalRefundsIndexRoute: typeof InternalGateInternalRefundsIndexRoute
}

const InternalGateRouteChildren: InternalGateRouteChildren = {
  InternalGateInternalAuditLogRoute: InternalGateInternalAuditLogRoute,
  InternalGateInternalFeesRoute: InternalGateInternalFeesRoute,
  InternalGateInternalIndexRoute: InternalGateInternalIndexRoute,
  InternalGateInternalMerchantsMerchantIdRoute:
    InternalGateInternalMerchantsMerchantIdRoute,
  InternalGateInternalMerchantsIndexRoute:
    InternalGateInternalMerchantsIndexRoute,
  InternalGateInternalRefundsIndexRoute: InternalGateInternalRefundsIndexRoute,
}

const InternalGateRouteWithChildren = InternalGateRoute._addFileChildren(
  InternalGateRouteChildren,
)

interface MarketingRouteChildren {
  MarketingDocsRoute: typeof MarketingDocsRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingDocsRoute: MarketingDocsRoute,
  MarketingIndexRoute: MarketingIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PortalTokenRouteChildren {
  PortalTokenCardUpdatedRoute: typeof PortalTokenCardUpdatedRoute
  PortalTokenInvoicesRoute: typeof PortalTokenInvoicesRoute
  PortalTokenPlansRoute: typeof PortalTokenPlansRoute
  PortalTokenIndexRoute: typeof PortalTokenIndexRoute
}

const PortalTokenRouteChildren: PortalTokenRouteChildren = {
  PortalTokenCardUpdatedRoute: PortalTokenCardUpdatedRoute,
  PortalTokenInvoicesRoute: PortalTokenInvoicesRoute,
  PortalTokenPlansRoute: PortalTokenPlansRoute,
  PortalTokenIndexRoute: PortalTokenIndexRoute,
}

const PortalTokenRouteWithChildren = PortalTokenRoute._addFileChildren(
  PortalTokenRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  InternalGateRoute: InternalGateRouteWithChildren,
  MarketingRoute: MarketingRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  InternalLoginRoute: InternalLoginRoute,
  PortalTokenRoute: PortalTokenRouteWithChildren,
  PayMerchantSlugPlanSlugRoute: PayMerchantSlugPlanSlugRoute,
  PlansMerchantSlugPlanSlugSuccessRoute: PlansMerchantSlugPlanSlugSuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
